// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBook(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function GetBooks():Promise<Array<Record<string, any>>>;

export function GetFileContent(arg1:string):Promise<string>;

export function OpenBook(arg1:string):Promise<string>;

export function OpenDirectoryPicker():Promise<string>;

export function OpenFilePicker():Promise<string>;

export function RemoveBook(arg1:string):Promise<void>;

export function ScanDirectory(arg1:string):Promise<Array<Record<string, any>>>;

export function SetLibraryPath(arg1:string):Promise<void>;
