// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBook(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddBook'](arg1, arg2, arg3, arg4, arg5);
}

export function GetBooks() {
  return window['go']['main']['App']['GetBooks']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function OpenBook(arg1) {
  return window['go']['main']['App']['OpenBook'](arg1);
}

export function OpenDirectoryPicker() {
  return window['go']['main']['App']['OpenDirectoryPicker']();
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function RemoveBook(arg1) {
  return window['go']['main']['App']['RemoveBook'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SetLibraryPath(arg1) {
  return window['go']['main']['App']['SetLibraryPath'](arg1);
}
